kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# uncomment below content to enable nodes to pull images from private docker registry
#containerdConfigPatches:
#  - |
#    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
#      endpoint = ["http://<your-docker-registry-host>:5000"]
nodes:
  - role: control-plane
    image: jacksonarthurclark/aiopslab-kind-arm:latest
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
  - role: worker
    image: jacksonarthurclark/aiopslab-kind-arm:latest
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev